services:
  ros2:
    build:
      context: ../..
      dockerfile: .docker/ubuntu_desktop/Dockerfile    

    container_name: ros2_dev_lab

    network_mode: host
    ipc: host

    privileged: true
    
    stdin_open: true
    tty: true

    volumes:
      # workspace manejable desde vscode
      - ../../ros2_ws:/ros2_ws
      # exposicion de monitor para graficos
      - /tmp/.X11-unix:/tmp/.X11-unix
      # exposicion de puertos externos
      - /dev:/dev
    
    environment:
      # canal dds de comunicación
      ROS_DOMAIN_ID: 2
      # forzamos conexión con una ip
      ROS_STATIC_PEERS: 192.168.5.66
      # acceso al display
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      LIBGL_ALWAYS_SOFTWARE: 1
