services:
  ros2:
    build:
      context: ../..
      dockerfile: .docker/ubuntu_edge/Dockerfile    

    container_name: ros2_edge

    network_mode: host
    ipc: host

    privileged: true
    
    stdin_open: true
    tty: true

    volumes:
      # workspace manejable desde vscode
      - ../../ros2_ws:/ros2_ws
      # exposicion de puertos externos
      - /dev:/dev
    
    environment:
      # canal dds de comunicación
      ROS_DOMAIN_ID: 2
      # forzamos conexión con una ip
      ROS_STATIC_PEERS: 192.168.68.60